name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Update file on server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: / 

      - name: Create restart file
        run: |
          mkdir -p restart-tmp
          date > restart-tmp/restart.txt
          echo "Restarting server at $(date)" > restart-tmp/restart.txt
        shell: bash

      - name: Restart server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./restart-tmp/
          server-dir: /tmp/
